//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string REMEN_BEZOBASNOSTI = "remen_bezobasnosti";
        
        public const string DAVLENIE_KRESLA = "davlenie_kresla";
        
        public const string BRAKE_ATACK = "brake_atack";
        
        public const string LEFT_POVOROT = "left_povorot";
        
        public const string RIGHT_POVOROT = "right_povorot";
        
        public const string LEFT_SELECT = "left_select";
        
        public const string RIGHT_SELECT = "right_select";
    }
}
